// Package slug derives the URL identifiers used for public fiction and chapter
// addresses (docs/08 - Database Design.md §35).
//
// It is shared rather than duplicated per domain: novels and chapters both need
// the same character set and the same collision strategy, and two copies would
// eventually disagree about which characters are legal - at which point a slug
// generated by one domain would fail the other's validation.
package slug

import (
	"crypto/rand"
	"strings"
	"unicode"
	"unicode/utf8"
)

// MaxLength bounds a generated slug. Both columns are VARCHAR(240), leaving room
// for a uniqueness suffix on top of this.
const MaxLength = 200

// Fallback is used when a title yields no slug characters at all.
const Fallback = "fiction"

// thaiRange is the Thai block, U+0E00–U+0E7F.
//
// A slug is now ASCII: Make drops Thai rather than keeping it or romanising
// it. A Thai slug looks fine in the address bar and becomes a wall of
// %E0%B8 the moment anyone pastes the link anywhere, and a romanised one turns
// a title into something its own author does not recognise.
//
// Thai is still ACCEPTED here, and that is load-bearing: any slug generated
// before this change is still resolvable, so an address that is already out in
// the world keeps working.
var thaiRange = &unicode.RangeTable{
	R16: []unicode.Range16{{Lo: 0x0E00, Hi: 0x0E7F, Stride: 1}},
}

// IsSlugRune reports whether r may appear in a slug.
func IsSlugRune(r rune) bool {
	switch {
	case r >= 'a' && r <= 'z':
		return true
	case r >= '0' && r <= '9':
		return true
	case r == '-':
		return true
	case unicode.In(r, thaiRange):
		return true
	}
	return false
}

// isASCIISlugRune is what Make will WRITE: the strict half of IsSlugRune.
// Validation stays wider so older, Thai-bearing slugs keep resolving.
func isASCIISlugRune(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
}

// Valid reports whether raw has the shape Make produces.
//
// Used to screen a path parameter before it reaches the database, so a hostile
// reference is rejected by shape rather than by a failed lookup.
func Valid(raw string) bool {
	if raw == "" || utf8.RuneCountInString(raw) > MaxLength {
		return false
	}
	for _, r := range raw {
		if !IsSlugRune(r) {
			return false
		}
	}
	return true
}

// Make derives a slug from a title.
//
// ASCII only: letters, digits, and single hyphens. Anything else - Thai,
// emoji, punctuation - collapses into a hyphen. A title with no ASCII words in
// it therefore produces nothing, and the caller substitutes Fallback plus a
// short suffix rather than this function inventing a transliteration nobody
// asked for.
func Make(title string) string {
	var b strings.Builder
	b.Grow(len(title))

	lastHyphen := true // suppresses leading hyphens
	for _, r := range strings.ToLower(strings.TrimSpace(title)) {
		switch {
		case isASCIISlugRune(r):
			b.WriteRune(r)
			lastHyphen = false
		case !lastHyphen:
			b.WriteRune('-')
			lastHyphen = true
		}
	}
	return truncate(strings.Trim(b.String(), "-"))
}

// truncate cuts to the length limit on a rune boundary, then trims any hyphen
// the cut exposed.
func truncate(value string) string {
	runes := []rune(value)
	if len(runes) <= MaxLength {
		return value
	}
	return strings.Trim(string(runes[:MaxLength]), "-")
}

// suffixAlphabet excludes vowels and easily confused characters, so a generated
// suffix cannot spell something unintended and stays easy to read aloud.
const suffixAlphabet = "bcdfghjkmnpqrstvwxz23456789"

const suffixLength = 6

// Candidate returns the slug to try on a given attempt.
//
// Attempt 0 is the clean slug. Later attempts append random characters, and the
// base is shortened first so the result still fits the column.
//
// The suffix is random rather than sequential: a counter would let anyone
// enumerate how many fictions share a title, including private drafts.
func Candidate(base string, attempt int) (string, error) {
	if base == "" {
		base = Fallback
	}
	if attempt == 0 {
		return base, nil
	}

	suffix, err := randomSuffix(suffixLength)
	if err != nil {
		return "", err
	}

	runes := []rune(base)
	if len(runes)+len(suffix)+1 > MaxLength {
		base = strings.Trim(string(runes[:MaxLength-len(suffix)-1]), "-")
		if base == "" {
			base = Fallback
		}
	}
	return base + "-" + suffix, nil
}

func randomSuffix(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	out := make([]byte, n)
	for i, b := range buf {
		out[i] = suffixAlphabet[int(b)%len(suffixAlphabet)]
	}
	return string(out), nil
}

// TokenLength is how long a generated address token is.
//
// Since the 2026-08 address review (docs/SLUGS.md), a NEW fiction or chapter's
// slug is this token ALONE - the title never enters the address. A title-based
// address freezes at creation, so every rename leaves a URL asserting a name
// the work no longer has; a token asserts nothing, so it can be permanent.
// Eight characters from the 27-symbol alphabet is ~2.8e11 combinations: sparse
// enough that addresses cannot be enumerated, short enough to share.
const TokenLength = 8

// NewToken returns a fresh address token - the whole slug of newly created
// work (docs/SLUGS.md). Random, never derived from the title, so renaming a
// work can never strand its address or leave it lying about the title.
func NewToken() (string, error) {
	return randomSuffix(TokenLength)
}

// IsToken reports whether raw has the exact shape NewToken produces. Legacy
// tooling that regenerates title-based slugs uses this to leave token-era
// addresses alone.
func IsToken(raw string) bool {
	if len(raw) != TokenLength {
		return false
	}
	for _, r := range raw {
		if !strings.ContainsRune(suffixAlphabet, r) {
			return false
		}
	}
	return true
}

// PublicIDLength is how long a fiction's short handle is.
//
// Six characters from a 27-symbol alphabet is ~387 million combinations - far
// past the point where a collision matters for a platform this size, and still
// short enough to say out loud.
const PublicIDLength = 6

// NewPublicID returns a fresh short handle.
//
// It uses the same vowel-free, confusion-free alphabet as the uniqueness
// suffix, so a handle cannot spell a word by accident and cannot be misheard as
// another one.
func NewPublicID() (string, error) {
	return randomSuffix(PublicIDLength)
}

// WithPublicID is the address of a fiction: its title, then its own handle.
//
//	genshin-impact-x-reader-headcanon-one-shot-collection-b7k2m9
//
// Every fiction gets the same shape, so two writers who choose the same title
// get addresses that differ in the last six characters instead of one of them
// getting a bare slug and the other a decorated one. A title with no ASCII in
// it becomes `fiction-<handle>`, which is still a real address rather than a
// percent-encoded one.
func WithPublicID(title, publicID string) string {
	base := Make(title)
	if base == "" {
		// A bare handle is a valid address but reads like a tracking code.
		// The generic word costs nothing and tells a reader what they are
		// looking at: /novel/fiction-b7k2m9.
		return Fallback + "-" + publicID
	}
	// Leave room for the handle and its hyphen.
	runes := []rune(base)
	if limit := MaxLength - len(publicID) - 1; len(runes) > limit {
		base = strings.Trim(string(runes[:limit]), "-")
		if base == "" {
			return Fallback + "-" + publicID
		}
	}
	return base + "-" + publicID
}
