// Package storage is the object-storage boundary (docs/07 §22: "S3-compatible
// storage. The exact provider can change later.").
//
// The interface is deliberately tiny and S3-shaped - opaque keys, whole-object
// reads and writes - so the media domain never learns which backend holds the
// bytes (docs/07 §65 "replaceable externally"). Two kinds of backend are
// expected over the platform's life:
//
//	Local - files under a configured directory; the development backend
//	        (docs/14 §56 "Local object storage emulator"), no external
//	        dependency, and the same dual-implementation pattern the rate
//	        limiter and the notification queue already use.
//	S3    - a future adapter for production object storage; it slots in here
//	        without touching the media domain.
//
// Keys are always GENERATED by the media service ({media_type}/{uuid}.{ext});
// nothing user-controlled ever reaches this package, which is what makes the
// path handling below a defence in depth rather than the security boundary.
package storage

import (
	"errors"
	"io"
)

// ErrNotFound reports a key with no object behind it.
var ErrNotFound = errors.New("object not found")

// Store is the narrow slice of object storage the media domain needs.
type Store interface {
	// Put writes an object under key, creating or replacing it atomically.
	Put(key string, contents io.Reader) error

	// Open returns a reader over the object's bytes. The caller closes it.
	Open(key string) (io.ReadCloser, error)

	// Delete removes the object. Deleting an absent key is NOT an error -
	// deletion is idempotent, like every other delete on the platform
	// (docs/09 §33).
	Delete(key string) error
}
