// Package notifications implements per-user notification delivery
// (docs/08 §23, docs/09 §23 and §44 Phase 6 - the second half of the
// Interaction phase).
//
// Notifications are generated by BACKEND EVENTS, never by the frontend
// (docs/07 §37): a domain action (publish, comment, follow) enqueues an event,
// and a background worker turns it into notification rows asynchronously
// (docs/09 §23 "Notifications should generally be generated asynchronously",
// docs/07 §27). The producing request never waits for fan-out.
//
// The package deliberately does not import chapters, comments, or library -
// those domains emit through their own consumer-defined Notifier interfaces,
// which this package's Service satisfies. Dependencies stay one-directional.
package notifications

import (
	"time"

	"github.com/google/uuid"
)

// Type is the notification kind (docs/08 §23.1). Stored as VARCHAR, not an
// enum: the documented list is explicitly "Examples", and adding a kind must
// not need a migration.
type Type string

const (
	TypeNewFollower  Type = "new_follower"
	TypeNewComment   Type = "new_comment"
	TypeCommentReply Type = "comment_reply"
	TypeNovelUpdate  Type = "novel_update"
	// TypeCommunityReaction is the reaction notification docs/08 §23.1
	// reserved for the community phase.
	TypeCommunityReaction Type = "community_reaction"
	// TypeModeration is docs/01 §26's "Moderation notification": your content
	// or account was acted on. It carries NO actor - sanctioned users must not
	// learn which individual moderator acted (docs/11 §39).
	TypeModeration Type = "moderation"
	// TypeAI tells a writer their asynchronous AI job finished (docs/12 §27
	// "Notify frontend"). It is a system notification about the requester's OWN
	// job, so it carries no actor.
	TypeAI     Type = "ai"
	TypeSystem Type = "system"
	// TypeSubscriptionActive tells a reader their Premium payment was verified
	// and their subscription is now active (Phase 11). A system notification
	// about the recipient's OWN subscription, so it carries no actor.
	TypeSubscriptionActive Type = "subscription_active"
	// TypeSubscriptionPaymentFailed tells a reader their Premium payment was
	// rejected and they may try again. Also actor-less.
	TypeSubscriptionPaymentFailed Type = "subscription_payment_failed"
)

// Entity types for the polymorphic (entity_type, entity_id) reference
// (docs/08 §23.1). Community entities are distinct from fiction ones because
// their ids live in different tables - a client resolving entity_id must know
// which surface to open.
const (
	EntityUser             = "user"
	EntityComment          = "comment"
	EntityChapter          = "chapter"
	EntityNovel            = "novel"
	EntityCommunityPost    = "community_post"
	EntityCommunityComment = "community_comment"
	EntityMedia            = "media"
	EntityAIRequest        = "ai_request"
	EntitySubscription     = "subscription"
)

// Actor is the public card of who triggered the notification - nil for system
// notifications, and cleared if the actor's account was hard-deleted
// (the schema's ON DELETE SET NULL).
type Actor struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName *string   `json:"display_name,omitempty"`
	AvatarURL   *string   `json:"avatar_url,omitempty"`
}

// Notification is one delivery row.
type Notification struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	Actor       *Actor
	Type        Type
	EntityType  *string
	EntityID    *uuid.UUID
	ReadAt      *time.Time
	CreatedAt   time.Time
}

// View is the API shape (docs/09 §23).
type View struct {
	ID         uuid.UUID  `json:"id"`
	Type       Type       `json:"type"`
	Actor      *Actor     `json:"actor,omitempty"`
	EntityType *string    `json:"entity_type,omitempty"`
	EntityID   *uuid.UUID `json:"entity_id,omitempty"`
	Read       bool       `json:"read"`
	ReadAt     *time.Time `json:"read_at,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
}

// Render builds the API view.
func (n *Notification) Render() View {
	return View{
		ID:         n.ID,
		Type:       n.Type,
		Actor:      n.Actor,
		EntityType: n.EntityType,
		EntityID:   n.EntityID,
		Read:       n.ReadAt != nil,
		ReadAt:     n.ReadAt,
		CreatedAt:  n.CreatedAt,
	}
}
